### ISSUE TITLE
DBLink has styles for variant "inline", but no Typescript definitions or documentation for it

### ISSUE THREAD

**Issue by milan-w** [db-ux-design-system/core-web#3995]
### Which generators are impacted?

- [x] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/db-ux-design-system/version-3/components/link#10447656

Laut Doku gibt es für die Komponente DBLink nur noch die Varianten "adaptive" und "brand". Im CSS für DBLink steht aber: 
 
```CSS
%db-default-link {
    &:not([data-variant="inline"]) {
      white-space: nowrap;
    }
    &[data-variant="inline"] {
      display: inline;
    }
...
}
```
source: packages/components/src/styles/internal/_link-components.scss

Zusätzlich findet sich dort die Definition `%db-link-height`, die dafür sorgt, dass alle .db-link Komponenten eine fixe block-size also Höhe bekommen:

```CSS
%db-link-height {
	display: inline-block;
	block-size: variables.$db-sizing-sm;
}
```

Da es nicht unüblich ist, dass verlinkte Text auch mal umbrechen, sollte die Anwendung dieser fixe Höhe mindestens optional sein. 

### Expected Behaviour

Either I'm able to use `data-variant="inline"` or the "inline" styles are applied when using `data-variant="adaptive"`.

### Browser version

None
